version: "3.9"

services:
  app:
    build: .
    container_name: fastapi_project
    ports:
      - "8000:8000"
    volumes:
      - ./app:/app/app     # Hot reload dla kodu aplikacji
      - ./app/data:/app/app/data  # Upewnij się, że dane są dostępne
    environment:
      - PYTHONUNBUFFERED=1
