version: "3.9"

services:
  app:
    build: .
    container_name: fastapi_project
    ports:
      - "8000:8000"
    volumes:
      - ./app:/app/app
      - ./app/data:/app/app/data
    environment:
      - PYTHONUNBUFFERED=1

  frontend:
    build:
      context: ./frontend
    container_name: react_frontend
    ports:
      - "3000:80"
    depends_on:
      - app
